name: Docker Compose build

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Without .env file.

      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v2.0
      #   with:
      #     envkey_TOKEN: ${{ secrets.BOT_TOKEN }}
      #     file_name: .env
      #     fail_on_empty: true
      #     sort_keys: false

      # - name: Docker-compose build
      #   run: docker-compose --env-file .env build

      - name: Docker-compose build
        run: docker compose build
